name: Python CI

on: [push, pull_request] # This tells GitHub to run the workflow on every push and pull request

jobs:
  test:
    runs-on: ubuntu-latest # Specifies the operating system for the runner
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10] # Test across different Python versions
    steps:
      - uses: actions/checkout@v4 # Checks out your repository code
      - name: Set up Python # Sets up the Python environment
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies # Installs packages listed in requirements.txt
        run: pip install -r requirements.txt
      - name: Run tests # Executes your tests using pytest
        run: pytest